console.log("------ swap two variable ------");
console.log("------- Before swapping -------");
var nameSweety="Sweety";
console.log("nameSweety :Sweety");
var nameCutie="Cutie";
console.log("nameCutie:Cutie");
console.log("------- swap three variable -------");
console.log("------- Before swapping ------");
var num1="100";
console.log("num1:100");
var num2="200";
console.log("num3:200");
var num3="300";
console.log("num3:300");
console.log("----------After swapping ---------");
var num1="200";
console.log("num1:200");
var num2="300";
console.log("num2:300");
var num3="400";
console.log("num3:400");
